import '../models/dress_model.dart';

List<Dress> sampleDresses = [
  Dress(
    name: "Floral Summer Dress",
    brand: "ABC Brand",
    starRating: 4.5,
    reviewCount: 28,
    offer: "20",
    description: "A beautiful floral summer dress made of lightweight fabric.",
    sizes: ["S", "M", "L"],
    price: 29.99,
    imageUrl: "assets/images/1.jpg",
  ),
  Dress(
    name: "Elegant Evening Gown",
    brand: "XYZ Designer",
    starRating: 4.2,
    reviewCount: 12,
    offer: "32",
    description: "An elegant evening gown with a mermaid silhouette.",
    sizes: ["M", "L", "XL"],
    price: 99.99,
    imageUrl: "assets/images/2.jpg",
  ),
  Dress(
    name: "Polka Dot Party Dress",
    brand: "Fashionista",
    starRating: 4.0,
    reviewCount: 8,
    offer: "15",
    description: "A fun and flirty polka dot party dress for any occasion.",
    sizes: ["S", "M", "L", "XL"],
    price: 39.99,
    imageUrl: "assets/images/3.jpg",
  ),
  Dress(
    name: "Sparkling Sequin Dress",
    brand: "Glamourous",
    starRating: 4.8,
    reviewCount: 37,
    offer: "30",
    description:
        "A dazzling sequin dress that will make you shine at any event.",
    sizes: ["XS", "S", "M", "L", "XL"],
    price: 79.99,
    imageUrl: "assets/images/4.jpg",
  ),
  Dress(
    name: "Casual Denim Dress",
    brand: "Jeans Co.",
    starRating: 4.1,
    reviewCount: 17,
    offer: "30",
    description: "A comfortable and stylish denim dress for casual wear.",
    sizes: ["S", "M", "L"],
    price: 49.99,
    imageUrl: "assets/images/5.jpg",
  ),
  Dress(
    name: "Tropical Print Maxi Dress",
    brand: "Island Vibes",
    starRating: 4.3,
    reviewCount: 9,
    offer: "25",
    description: "A vibrant and flowy maxi dress with a tropical print.",
    sizes: ["S", "M", "L"],
    price: 34.99,
    imageUrl: "assets/images/6.jpg",
  ),
  Dress(
    name: "Ruffled Party Dress",
    brand: "Chic Boutique",
    starRating: 4.7,
    reviewCount: 31,
    offer: "25",
    description: "A flouncy ruffled party dress that will turn heads.",
    sizes: ["S", "M", "L", "XL"],
    price: 69.99,
    imageUrl: "assets/images/7.jpg",
  ),
  Dress(
    name: "Striped A-line Dress",
    brand: "Fashion Forward",
    starRating: 4.4,
    reviewCount: 15,
    offer: "50",
    description: "A classic and timeless A-line dress with chic stripes.",
    sizes: ["M", "L", "XL"],
    price: 54.99,
    imageUrl: "assets/images/8.jpg",
  ),
  Dress(
    name: "Glamorous Ball Gown",
    brand: "Couture Dreams",
    starRating: 4.9,
    reviewCount: 42,
    offer: "30",
    description: "A glamorous ball gown fit for a princess.",
    sizes: ["S", "M", "L", "XL"],
    price: 149.99,
    imageUrl: "assets/images/9.jpg",
  ),
  Dress(
    name: "Cute and Comfy T-Shirt Dress",
    brand: "Casual Chic",
    starRating: 4.0,
    reviewCount: 6,
    offer: "17",
    description: "A cute and comfortable t-shirt dress for everyday wear.",
    sizes: ["S", "M", "L"],
    price: 24.99,
    imageUrl: "assets/images/10.jpg",
  ),
  Dress(
    name: "Vintage Lace Dress",
    brand: "Retro Style",
    starRating: 4.6,
    reviewCount: 24,
    offer: "10",
    description: "A vintage-inspired lace dress with a touch of nostalgia.",
    sizes: ["M", "L"],
    price: 59.99,
    imageUrl: "assets/images/11.jpg",
  ),
];
